### ISSUE TITLE
Default kernel path may conflict

### ISSUE THREAD

**Issue by pulser** [sonyxperiadev/kernel#112]
Per http://developer.sonymobile.com/knowledge-base/open-source/open-devices/aosp-build-instructions/how-to-build-aosp-lollipop-for-unlocked-xperia-devices/

The current local_manifest kernel path may conflict/clash with existing kernels from other devices.

Manifest places this kernel currently at kernel/, which probably contains kernels for other devices (say nexus, or whatever). It would probably be a good idea to adjust this manifest towards a subdirectory such as kernel/sony, so it won't clash with another OEM's kernel sources, if someone has more than one checked out.

kernel/sony may not be ideal if the user already has other sony non-unified kernels present, but I guess that's taking things to the n'th degree.

**Comment by jerpelea** [comment]
Thanks for notifying us 
we have updated the build guide to use "kernel/sony" path
