### ISSUE TITLE
Not poweroff

### ISSUE THREAD

**Issue by russel5** [sonyxperiadev/kernel#1152]
Hello i'm using Z3Compact and build twrp recovery with your kernel sources. No matter what branch of omnirom i'm using, if i made recovery with your sources the phone are not poweroff at all. It's just always reboot after some time, ie blackscreen - 5 or 10 sec - reboot
But if i'm using your official kernel sources, like 291, all works perfect, ie i'm pressed power off in recovery and phone off not reboot as with your aosp sources. Can you check this issues, thanks.
I'm using omni - 6.0 & 7.0 for compiling, with your sources or default and always get this issue.

**Comment by scafroglia93** [comment]
My Z3 got this problem when I charge the phone

@kholk

**Comment by russel5** [comment]
One more things
Poweroff not work not only in recovery - reboot - poweroff
It's not work in terminal via busybox
And it's a bug in this kernel sources
Phone always turn on

**Comment by russel5** [comment]
Seems like the latest commits for twrp fix this bug. Closed
