### ISSUE TITLE
[1.3.3] tulip sound

### ISSUE THREAD

**Issue by bartcubbins** [sonyxperiadev/kernel#1190]
On Tulip works mic, ear speaker and headphones but no sound in main speaker.
dmesg: https://gist.github.com/bartcubbins/e5bcab93a291e5d1d3ca875c63d78fe2

**Comment by mcgi5sr2** [comment]
@bartcubbins has this been resolved?

**Comment by bartcubbins** [comment]
@mcgi5sr2 still have this problem. did you have some ideas?

**Comment by tomty89** [comment]
does it not work only for calls or media as well?

**Comment by bartcubbins** [comment]
@tomty89 doesn't work at all

**Comment by bartcubbins** [comment]
ping @erikcas

**Comment by erikcas** [comment]
hi guys... The problem for me is that I donot have a tulip to test with. Developing on it was a while ago.
For this I would rather see a logcat then a dmesg.

**Comment by pablomh** [comment]
Hi @erikcas, there you go in case it's useful:

https://gist.github.com/pablomh/f4b46d1d470f47942de4aa7630d4b732
