### ISSUE TITLE
random32.so

### ISSUE THREAD

**Issue by mcgi5sr2** [sonyxperiadev/kernel#1210]
CC      lib/random32.o
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:179:50: error: expected ')' before numeric constant
 static DEFINE_TIMER(seed_timer, __prandom_timer, 0, 0);
                                                  ^
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c: In function '__prandom_timer':
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:188:2: error: 'seed_timer' undeclared (first use in this function)
  seed_timer.expires = jiffies + (40 * HZ + (prandom_u32() % (40 * HZ)));
  ^
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:188:2: note: each undeclared identifier is reported only once for each function it appears in
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:189:2: error: implicit declaration of function 'add_timer' [-Werror=implicit-function-declaration]
  add_timer(&seed_timer);
  ^
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c: In function 'prandom_start_seed_timer':
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:194:2: error: implicit declaration of function 'set_timer_slack' [-Werror=implicit-function-declaration]
  set_timer_slack(&seed_timer, HZ);
  ^
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:194:19: error: 'seed_timer' undeclared (first use in this function)
  set_timer_slack(&seed_timer, HZ);
                   ^
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c: At top level:
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/lib/random32.c:181:13: warning: '__prandom_timer' defined but not used [-Wunused-function]
 static void __prandom_timer(unsigned long dontcare)
             ^
cc1: some warnings being treated as errors
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/scripts/Makefile.build:308: recipe for target 'lib/random32.o' failed
make[2]: *** [lib/random32.o] Error 1
/home/mcgi5sr2/AOSP/android/system/kernel/sony/msm/Makefile:821: recipe for target 'lib' failed
make[1]: *** [lib] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:130: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

**Comment by kholk** [comment]
Did compile for me. Checking ASAP.

**Comment by lowtraxx** [comment]
Got the same errors here. Cleaned and tried again, but still failing to build.

**Comment by lowtraxx** [comment]
Adding #include <linux/timer.h> into random32.c fixes the build for me.

**Comment by ergoen** [comment]
In mainline <linux/sched.h> is included in random32.c, adding this include also fixes the compile problem (sched.h includes timer.h I suppose).

**Comment by mcgi5sr2** [comment]
https://github.com/torvalds/linux/commit/f6a570333e554b48ad589e7137c77c57809eee81

mainline commit that adds sched.h include

**Comment by jerpelea** [comment]
pr please

**Comment by mcgi5sr2** [comment]
https://github.com/torvalds/linux/commit/a6a9c0f1bf5a9a5faa605773ea75e0b93c3ab108

is the commit from mainline thats adds sched.h include

**Comment by kholk** [comment]
I'm on it.

**Comment by mcgi5sr2** [comment]
n1 @kholk
