### ISSUE TITLE
[UM.5.5.r1] broken sdcardfs

### ISSUE THREAD

**Issue by artem** [sonyxperiadev/kernel#1217]
Hello!
I tried to test sdcardfs on my Xperia XZ and it causes hang of some processes. For example, it's not possible to access "/sdcard/Telegram/Telegram Images/" in any way: Telegram itself (just hangs during start), file manager or command shell. Also, "adb install" causes system hang. After switching back to FUSE everything works flawlessly.
What can cause this issue?

P.S. Same occurs on stock ROM with stock kernel rebuilt to support sdcardfs

**Comment by bartcubbins** [comment]
@jerpelea LA.UM.5.5.r1 (3.18) is now EOL status.
