### ISSUE TITLE
Ivy DTB not found 

### ISSUE THREAD

**Issue by TitanNano** [sonyxperiadev/kernel#1274]
I'm trying to build 7.1 for my `Ivy (E6533)` device. Therefore I cloned the AOSP source as described in the instructions for android 7.1 Kernel 3.10 (https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/). At first I just built the recovery image to see if everything is working well. Unfortunately here I already encounter the first issue, when I try to boot the resulting `boot.img` or `recovery.img` with "fastboot boot boot.img`, it returns "FAILED (dtb not found)".

I know that the prebuild kernel already includes the dtb, so why is it not found here? Did I mess up something? I'd be glad if you could help me out here.

**Comment by jerpelea** [comment]
please flash the latest Sony software to get a bootloader update

**Comment by TitanNano** [comment]
@jerpelea I already unlocked my bootloader, so Device Companion told me that I can't update. Does this mean I have to lock it, update and then unlock it again? Thanks for your help

**Comment by jerpelea** [comment]
https://developer.sonymobile.com/open-devices/

here you have the flashtool for unlocked devices and resources for our project

**Comment by TitanNano** [comment]
@jerpelea I tried the flashtool, but it seems to only support the Z3+ (E6553) not the Z3+ Dual (E6533).

**Comment by jerpelea** [comment]
i will check with my coleagues

**Comment by kholk** [comment]
@TitanNano http://www.flashtool.net/downloads.php
Use this and flash your device

**Comment by TitanNano** [comment]
@kholk I have this tool, but how can I download the official firmware?

**Comment by kholk** [comment]
XperiFirm inside the tool itself.....

**Comment by TitanNano** [comment]
okay I got it to work, thank you guys.
