### ISSUE TITLE
Precompiled kernel AOSP

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#1519]
Hello,
I follow the instructions described on https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-nougat-for-unlocked-xperia-devices/  but the boot image does not contain the precompiled kernel.

I tried also to to put:
```
ifeq ($(TARGET_PREBUILT_KERNEL),)
   LOCAL_KERNEL := device/sony/aries/kernel
else
   LOCAL_KERNEL:= $(TARGET_PREBUILT_KERNEL)
endif
PRODUCT_COPY_FILES := \
                      $(LOCAL_KERNEL):kernel
```
in the kernel/sony/msm/Makefile and export TARGET_PREBUILT_KERNEL=my/sony/zImage, but without success.
 
Anyone have a idea?

Thank you in advance.

PS: I try to build a boot image for sony xperia Z3 compact

**Comment by jerpelea** [comment]
what android version do you try to bulit ?
did you use Kernel 3.10 or Kernel 4.4?

**Comment by ghost** [comment]
Nougat 7.1
I use the kernel 3.10

**Comment by jerpelea** [comment]
kernel 3.10 is provided for your device!

**Comment by ghost** [comment]
Thank you for your quick response.
I know but I need some features that's not exist in the default kernel config!

**Comment by jerpelea** [comment]
try the default one then we can start from there

**Comment by ghost** [comment]
the default one work without problems! But I need just for an example the /proc/kallsyms that doesn't exist in the default Kernel!

**Comment by jerpelea** [comment]
how do you build the kernel?

**Comment by ghost** [comment]
I use the branch LA.BR.1.3.3_rb2.14 for the kernel:
```
$ make aosp_shinano_aries_defconfig
$ make xconfig # enable some features
$ make -j<nb_core> # the zImage was built successfuly 
```
I put the zImage in the folder  device/sony/aries in the AOSP directory as described in the guide (https://developer.sonymobile.com/open-devices/how-to-build-and-flash-a-linux-kernel/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices/) and the arch/arm/boot/dts/msm8974pro-ac-shinano_aries.dtb to the folder device/sony/aries/dtbs (which doesn't exist by default). 

When I saw that doesn't wok I tried the alternative that I described in the first message.

I tried also unpacking the boot.img and replacing the Kernel (generated by AOSP) by the Kernel that I built from the the branch LA.BR.1.3.3_rb2.14. I used the "mkboot" tool, here is the img_info used for genereted the new boot image:

```
kernel=kernel
ramdisk=ramdisk
page_size=2048
kernel_size=8873136 # the size of the new compiled Kernel
ramdisk_size=1319350
base_addr=0x00000000
kernel_offset=0x00008000
ramdisk_offset=0x02000000
tags_offset=0x01e00000
cmd_line='console=ttyHSL0,115200,n8 vmalloc=300M androidboot.selinux=permissive msm_rtb.filter=0x3F ehci-hcd.park=3 coherent_pool=8M sched_enable_power_aware=1 user_debug=31 androidboot.hardware=aries buildvariant=userdebug'
board=""
format=gzip
```
the boot image was generated wihout error, but the phone doesn't boot.

Thank you @jerpelea.
