### ISSUE TITLE
LA.BR.1.3.3_rb2.14 Kernel Lmk bug

### ISSUE THREAD

**Issue by hzj5158888** [sonyxperiadev/kernel#1584]
lowmemorykill := Error open /dev/memcg/apps/xxxxxxxx

Enabled CONFIG_MEMCG

bug fixed

**Comment by jerpelea** [comment]
pr please

**Comment by hzj5158888** [comment]
@jerpelea weekend

**Comment by jerpelea** [comment]
Can you share more info howto replicate the error?
I tested the suzu device running Android 7.1 and I could not see this error

**Comment by jerpelea** [comment]
please post the bug in the bug tracker 
https://github.com/sonyxperiadev/bug_tracker
