### ISSUE TITLE
Eta for kernel 4.9 or newer?

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/kernel#1647]
Is there a ETA for kernel 4.9 or newer?
I don't need a high precise date, naming a month would be fine.

**Comment by jerpelea** [comment]
6.3_r1
enjoy

**Comment by MartinX3** [comment]
Thank you.

So 6.3 is Kernel 4.9
And 6.4 is Kernel 4.4?

Should't it be turned around?
And will 6.3 receive updates?
Last commit is from January, but the XZ2 is from april.

**Comment by jerpelea** [comment]
we are working on XZ2 devices and when devices will have official support there will be a blogost

**Comment by MartinX3** [comment]
Thank you for this information!
