### ISSUE TITLE
[aosp/LE.UM.2.3.2.r1.4] init/Kconfig:340: can't open file "kernel/irq/Kconfig"

### ISSUE THREAD

**Issue by MartinX3** [sonyxperiadev/kernel#1693]
System Ubuntu 18.04 / Linux Mint 19

I try to compile the XZ2 Akari kernel, but fail with this error:

```bash
$ make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE aosp_tama_akari_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
init/Kconfig:340: can't open file "kernel/irq/Kconfig"
scripts/kconfig/Makefile:112: recipe for target 'aosp_tama_akari_defconfig' failed
make[1]: *** [aosp_tama_akari_defconfig] Error 1
Makefile:544: recipe for target 'aosp_tama_akari_defconfig' failed
make: *** [aosp_tama_akari_defconfig] Error 2
```

Anyone know how to solve this problem?
"kernel/irq/Kconfig" does exist and my user has write and read permission. He owns this file.

**Comment by nathanchance** [comment]
I would try specifying an out folder

`make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE O=out aosp_tama_akari_defconfig`

**Comment by MartinX3** [comment]
Thank you for your fast response.

But sadly stil lthe same error

```bash
$ mkdir out
$ make mrproper
  CLEAN   scripts/basic
  CLEAN   scripts/kconfig

#### build completed successfully (8 seconds) ####

$ make ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE o=out aosp_tama_akari_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
init/Kconfig:340: can't open file "kernel/irq/Kconfig"
scripts/kconfig/Makefile:112: recipe for target 'aosp_tama_akari_defconfig' failed
make[1]: *** [aosp_tama_akari_defconfig] Error 1
Makefile:544: recipe for target 'aosp_tama_akari_defconfig' failed
make: *** [aosp_tama_akari_defconfig] Error 2

#### failed to build some targets (2 seconds) ####
```

**Comment by kholk** [comment]
This seems to be an issue with your own environment variables and/or your specific GNU Make version.

Please make sure that you are using stable packages from your distribution and that you did not apply custom configuration to GNU Make (the suspect comes from the unusual Android build system style build success/failure messages).

Also, next time, please open your bug reports on the bug_tracker repository here on the sonyxperiadev github.

Thanks!

**Comment by MartinX3** [comment]
Thx for your response and sorry, the next issue will be in the issue tracker.

My GNU make version is the standard one shipped with Ubuntu 18.04 Bionic
"4.1-9.1ubuntu1"

And I did not change the GNU make settings.
I made a REPO init and REPO sync and used a fresh downloaded cross compiler.

Could it be the new Ubuntu 18.04?

Is there  a docker image or another kind of working build environment configuration I could install and test?

PS: My system is fresh installed.

**Comment by YumeMichi** [comment]
No build errors on archlinux.
https://i.imgur.com/rvOy5A0.png

**Comment by MartinX3** [comment]
Hmm, maybe someone has the same problem on another Ubuntu 18.04?
Then something is in Ubuntu or in this project wrong.

If not, I did something wrong.
But I don't know what.

Or maybe I've got a package version with a bug.
Ubuntu is not a rolling release. (So I am stuck with Kernel 4.15 at the moment, too [I don't want a non Ubuntu kernel])
But who knows the weird cause.

**Comment by artem** [comment]
What's the creation time of that `kernel/irq/Kconfig`? I have got similar error with files that had creation date of 01-01-1970, GNU make simply couldn't find them for some reason

**Comment by MartinX3** [comment]
That are the file informations:

```bash
martin@deus-ex-machina:/media/martin/extLinux/Develop/OpenSource/C++/Sony/XZ2/platform_manifest_twrp_omni/kernel/sony/akari/kernel/kernel/irq$ stat Kconfig 
  File: Kconfig
  Size: 2684      	Blocks: 8          EA Block: 4096   Normale File
Device: 814h/2068d	Inode: 72759916    Symlinks: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  martin)   Gid: ( 1000/  martin)
Access    : 2018-07-23 23:29:14.095936233 +0200
Modified: 2018-07-23 22:59:51.083621504 +0200
Changed   : 2018-07-23 22:59:51.083621504 +0200
 Birth    : -

```

**Comment by kholk** [comment]
Okay, that's a _very_ long path.
Really, shorten it out, it's really too long.

**Comment by MartinX3** [comment]
Thank you! A shorter path fixed this problem.
According to
https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices
and
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/build-aosp-nougat-8-1-oreo-4-4
I did the steps, but if I run "make" or "make bootimage" I get the following error:

```bash
martin@deus-ex-machina:/media/martin/extLinux/Develop/android$ make -j 8 bootimage
[...]
build/core/base_rules.mk:390: warning: ignoring old commands for target `out/target/product/akari/vendor/etc/gps.conf'
ninja: error: 'kernel/sony/msm-4.4/kernel/arch/arm64/configs/aosp_tama_akari_defconfig', needed by '/media/martin/extLinux/Develop/android/out/target/product/akari/obj/KERNEL_OBJ/.config', missing and no known rule to make it
23:45:32 ninja failed with: exit status 1

#### failed to build some targets (58 seconds) ####
```

So I assume that it is too early to build a 4.9 kernel for tama/akari (XZ2) ?
If yes, could you give me a ETA?
Or did I something wrong?

**Comment by YumeMichi** [comment]
4.4 kernel? 4.9 kernel?
```
error: 'kernel/sony/msm-4.4/kernel/arch/arm64/configs/aosp_tama_akari_defconfig'
```

**Comment by MartinX3** [comment]
@YumeMichi I choose only ARM64 and the tama akari defconfig. (Lunch h8266 thing)
Tama akari is the XZ2 Plattform and the first with Kernel 4.9.
There is no Kernel 4.4 for it.

**Comment by YumeMichi** [comment]
@MartinX3 Why your kernel path for tama akari is kernel/sony/msm-4.4?
https://github.com/sonyxperiadev/local_manifests/blob/master/LE.UM.2.3.2.r1.4.xml#L6

**Comment by MartinX3** [comment]
@YumeMichi I don't know
In the msm-4.9 folder are the right files.
I only sync, lunch and make.
Does your buildsystem produce the same error for the lunch h8266 config?

But the kernel branch for the precompiled 4.9 kernels is empty, too. 
https://github.com/sonyxperiadev/vendor-sony-kernel

**Comment by kholk** [comment]
The 4.9 kernel is not ready yet for Tama.
Only recovery currently works, you can boot to Android if you hack the security, but the display hal currently crashes. 

If you want to go on, you can generate the dtb image and put it in that folder, that way your build will succeed. 

If you're not an experienced developer, I'd consider waiting for us to fix the last issues before trying to boot it!

**Comment by MartinX3** [comment]
@kholk 
Good to know, thank you!

I only want to compile the dtb for the recovery image.

I followed the instructions in README_Xperia, but get

```
/media/martin/extLinux/Develop/android/kernel/sony/msm-4.9$ make CONFIG_BUILD_ARM64_DT_OVERLAY=y O=./out sdm845-perf_defconfig
make: *** Keine Regel, um „sdm845-perf_defconfig“ zu erstellen.  Schluss.

#### failed to build some targets  ####
```

But the file sdm845-perf_defconfig exists.

Edit:
I removed the msm-4.9 folder and used the akari kernel from the sony developer site.
Now it creates the Image.gz-dtb

THX for your information and have a nice day. :)

**Comment by kholk** [comment]
You're welcome!
