### ISSUE TITLE
Whats is missing for SDXC

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/kernel#1771]
Plattform: sony-nile
Android version: 8.1 /Mer-Hybris
Symptoms: no /dev/mmcblk1 device

The xperia open devices page states that only sdcards that are <=32GB are supported.
What is missing on SDXC kernel support?

**Comment by kholk** [comment]
The page should be updated.
The devices support more capacity. 
I use a 128GB uSD myself. 

@jerpelea please :D


EDIT: Ugh, I didn't notice that this wasn't the bug tracker!

**Comment by jerpelea** [comment]
please post bugs in the bugtracker git

**Comment by Thaodan** [comment]
@kholk which device?
