### ISSUE TITLE
Where is the defconfig for Xperia L1 ?

### ISSUE THREAD

**Issue by mluis** [sonyxperiadev/kernel#1829]
Is there an official defconfig for Xperia L1 or a compatible one?

tks

**Comment by jerpelea** [comment]
open devices does not support Xperia L1 and there is no config for this device

**Comment by mluis** [comment]
Is there a list of the open devices?

**Comment by danielgusvt** [comment]
@mluis https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/
https://github.com/sonyxperiadev/bug_tracker/blob/master/README.md

**Comment by bartcubbins** [comment]
PS: The list is larger at 3.10 kernel, but anyway L1 isn't supported by Sony Open Device Program, sorry

**Comment by mluis** [comment]
I bought the only cool device that's not supported.. :( such a luck.
