### ISSUE TITLE
Logo staying in recovery on eagle

### ISSUE THREAD

**Issue by galaxyfreak** [sonyxperiadev/kernel#188]
This seems like a framebuffer derp, not a major bug, so I've decided to fill an issue to let you guys know.

Sony logo stay shown while in recovery.

**Comment by jerpelea** [comment]
should be fixed now!
please test for your usecase

**Comment by Entropy512** [comment]
I'm encountering this same issue on leo - which commit fixed this on eagle?

EDIT: Hmm, I am currently using aosp/AU_LINUX_ANDROID_LA.BF.2.1_RB1.05.00.00.173.012 on eagle - should I be using aosp/AU_LINUX_ANDROID_LA.BF64.1.1_RB1.05.00.00.172.042 instead?

**Comment by galaxyfreak** [comment]
They hoped commits here: https://github.com/sonyxperiadev/kernel/commits/aosp/AU_LINUX_ANDROID_LA.BF.2.1_RB1.05.00.00.173.012?page=2 (March 10) would fix it, but it's not.
And, don't use BF64 branch, doesn't boot yet.

**Comment by erikcas** [comment]
on omnirom / twrp no such a problem so maybe check cm recovery sources?

**Comment by galaxyfreak** [comment]
Fixed on BF64.
