### ISSUE TITLE
Latest update on LA.UM.6.4.r1 broke compilation

### ISSUE THREAD

**Issue by Thaodan** [sonyxperiadev/kernel#1997]
The latest update to LA.UM.6.4.r1 brought the commit:
e5d7620af2fd50b50c3a37cd7a27e366e897747

Which results in
```
../../../../../../kernel/sony/msm-4.4/kernel/drivers/platform/msm/ipa/ipa_v3/ipa_rt.c: In function 'ipa3_reset_rt':
../../../../../../kernel/sony/msm-4.4/kernel/drivers/platform/msm/ipa/ipa_v3/ipa_rt.c:1473:13: error: 'struct ipa3_rt_entry' has no member named 'rule_id_valid'
    if (!rule->rule_id_valid)
             ^
make[6]: *** [drivers/platform/msm/ipa/ipa_v3/ipa_rt.o] Error 1
make[6]: *** Waiting for unfinished jobs....

```
The issue is that /rule_id_valid/ was only added in:
https://github.com/sonyxperiadev/kernel/commit/d0c2a1ebcecc549d1803787c1c9d78f3ed308a9e

Which is not inside this true.
So what should happen revert the commit or apply depended commit?

**Comment by jerpelea** [comment]
please add the missing commit and PR

**Comment by Thaodan** [comment]
Missing commit?
The commit thats the issue is mentioned above and the other pr is not part of 
this bug,  I discovered it afterwards.

**Comment by Thaodan** [comment]
Currently I reverted the mentioned and the kernel builds fine now.
I just asked if reverting or porting the depended commit is better.

**Comment by kholk** [comment]
@Thaodan Revert the commit. It's the best choice since k4.4 is in feature freeze since... A very long time ago.
The commit that introduces the fix also introduces a new feature, which will never be used anyway ;)

**Comment by Thaodan** [comment]
Ok, I already did tat. I'll make a pr on that later.

**Comment by jerpelea** [comment]
Please rever the commit 
the branch is feature freeze

**Comment by Thaodan** [comment]
This depends also partly #1998.

**Comment by Thaodan** [comment]
Fixed by: https://github.com/sonyxperiadev/kernel/commit/08932cbccbf7faaa049755da5ad7ae6aabcccba7
