### ISSUE TITLE
Why is there no suzuran defconfig

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [sonyxperiadev/kernel#2180]
I ask myself why is there no suzuran defconfig?
https://developer.sony.com/develop/open-devices/guides/kernel-compilation-guides/how-to-build-and-flash-a-linux-kernel-for-aosp-supported-devices#tutorial-step-3
The ota is running out and we had problems building new roms without official sources.

Isn't Sony able to provide some code to prevent the Sony Xperia 5 (compact/premium/normal) from getting sorted out and land in the garbage?

**Comment by jerpelea** [comment]
unfortunately not for the latest branch but you can use the LA.BR.1.3.3_rb2.14 branch for your Android build

**Comment by sorryusernameisalreadytaken** [comment]
THX for that. Sadly is it quite old :)

Can you tell me the reason why there is nothing for the latest branch? The Z3 seems to be supported.

**Comment by jerpelea** [comment]
because it is old and does not have the needed blobs

**Comment by oshmoun** [comment]
the z3 is definitely not supported on the latest branch. you are probably mixing up xz3 and z3 :)

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> the z3 is definitely not supported on the latest branch. you are probably mixing up xz3 and z3 :)

oh yeah you right.



> 
> 
> because it is old and does not have the needed blobs

Ok, it is just development time for such an old device. That's a pity, because especially these need some support in the last moves to be able to be maintained by free developers.

**Comment by jerpelea** [comment]
@sorryusernameisalreadytaken you can use the the branch I specified for your project since it has compatible blobs released on our website
