### ISSUE TITLE
contribute?

### ISSUE THREAD

**Issue by nycbjr** [sonyxperiadev/kernel#24]
Hi there I have an update to include/linux/msm_vidc_dec.h to allow inline building wiht newer versions of qcom-caf in cm based roms.  How do I push to you?

**Comment by Kali-** [comment]
this kernel is intended to be used for AOSP

btw i have no plan to use it as a base on CM11 (i dont see any reason to change it at this stage), but will be probably the base for CM12

**Comment by jerpelea** [comment]
this kernel is for AOSP base 
you have to adapt your custom rom to use it
