### ISSUE TITLE
boot loader unlock does not work on the Sony Xperia 5 iii

### ISSUE THREAD

**Issue by Pelunka2** [sonyxperiadev/kernel#2452]
Hi, I can't unlock my device: Sony Xperia 5 lll
I'm in the fastboottd menu: https://i.imgur.com/k7BhMZG.png
but my commands unlock doesn't work: https://i.imgur.com/TSkyMrm.png

Test Emma: https://i.imgur.com/MLd5zId.png

"FAILED (remote: 'Command not supported in default implementation')"

-OEM Unlocking = Enabled
-USB debugging = Enabled

Please, what am I doing wrong ?

**Comment by jerpelea** [comment]
@Pelunka2  please boot the device in regular fastboot (blue led) then try to unlock the devices

**Comment by jerpelea** [comment]
please use the bug tracker
https://github.com/sonyxperiadev/bug_tracker/
