### ISSUE TITLE
Sony debug UART port

### ISSUE THREAD

**Issue by phodina** [sonyxperiadev/kernel#2558]
Hi,

could you please help me with accessing the UART debug port?

I've modified Pine64 micro SD card extension cable and soldered wires so it can be connected to the UART<->USB adapter.

However, looking on the osciloscope I see only CLK signal for the SD card.
![image](https://user-images.githubusercontent.com/2997905/233453301-3971ec09-116b-4aa7-a832-2f6ae42c174f.png)

Is there something else that should be done and is missing in the documentation?
https://developer.sony.com/develop/open-devices/guides/access-uart-ports

My phone is Xperia XZ3. But it should be applicable for other newer models with Debug UART on the micro SD interface.

**Comment by phodina** [comment]
Hi @konradybcio @jerpelea

as you contribute to Sony kernels could I ask you for help.

The Sony developer site there should be UART port accessible with the right equipment. Though they just show SDcard with 2 pins (Tx and GND) whithout any additional steps.

Would you happen to know how to get it working? Or someone that might help?
Do you use it?

Here's the photo of the debug board I modified from micro SDcard adapter
https://forum.xda-developers.com/t/uart-pins-sony-xperia-5-devices.4530005/

**Comment by MarijnS95** [comment]
@phodina you have to enable the console via kernel-devicetree and/or cmdline (see Android devicetree), and may even need to toggle a pin or two.

More curiously, what are you intending to use the UART function for?

**Comment by MarijnS95** [comment]
That is, start at:

https://github.com/sonyxperiadev/device-sony-tama/blob/3e6fd755be9891d1d59113538efc712895acd1cd/PlatformConfig.mk#L34-L35

(~And see if the driver handling this cmdline is compiled in~ EDIT: probably is, because Bluetooth hardware communicates over a (HS) UART too)

You should at the very least already have seen S1boot _when rebooting the phone_, afaik.

**Comment by phodina** [comment]
> @phodina you have to enable the console via kernel-devicetree and/or cmdline (see Android devicetree), and may even need to toggle a pin or two.
> 
> More curiously, what are you intending to use the UART function for?

So this is UART console just for the Kernel. I won't be able to see bootlog from the earlier stage of bootloader?

The interest is to run on Xperia XZ3 phone [PostmarketOS](https://wiki.postmarketos.org/wiki/Devices) - well port it first. The SDM845 is well supported.

**Comment by konradybcio** [comment]
> > @phodina you have to enable the console via kernel-devicetree and/or cmdline (see Android devicetree), and may even need to toggle a pin or two.
> > More curiously, what are you intending to use the UART function for?
> 
> So this is UART console just for the Kernel. I won't be able to see bootlog from the earlier stage of bootloader?
> 
> The interest is to run on Xperia XZ3 phone [PostmarketOS](https://wiki.postmarketos.org/wiki/Devices) - well port it first. The SDM845 is well supported.

Just be careful with the UFS.. Enabling it on a non-SODP or non-stock kernel will irrecoverably kill your device (fw quirk)

**Comment by MarijnS95** [comment]
> So this is UART console just for the Kernel. I won't be able to see bootlog from the earlier stage of bootloader?

As said you should have already seen S1boot come across (if not, maybe something is wrong with the UART, or they disabled it "somehow"), I thought you were trying to see it from the SODP kernel.

At least that's what I observed on the Xperia X and Xperia XA2 Ultra: S1boot UART logs are always available, because that's outside the territory that we can modify.

> The interest is to run on Xperia XZ3 phone [PostmarketOS](https://wiki.postmarketos.org/wiki/Devices) - well port it first. The SDM845 is well supported.

I know. I contribute to the mainline kernel _daily_ with features and fixes, and hope pmOS starts using our efforts some day. No immediate need for UART, though.

What's the current status, and what kernel do you intend to use?

**Comment by phodina** [comment]
Thanks I know. There's big warning on the https://wiki.postmarketos.org/wiki/SDM845_Mainlining

Also on the mainline the UFS is disabled.

Currently I just flash the mainline kernel and I'm left stranded as it does probably not boot. So I'd like to get more insight in what's happening. That's why I asked about the serial line.

**Comment by phodina** [comment]
I'm using this repo for the kernel https://gitlab.com/sdm845-mainline/linux

Current status is that I made the device package and I'm able to build the abootimg.

I've attempted to flash it. But without the screen or serial it's hard to tell what happens.

**Comment by MarijnS95** [comment]
@phodina we have more commits for Tama/XZ3 over at https://github.com/SoMainline/linux/commits/marijn/longbois-next, I booted that branch just this morning. There's also a defconfig.

You might be booting from an SDcard, and I had to explicitly force the cmdline to use `mmcblk0` because the bootloader cmdline otherwise takes preference:

https://github.com/SoMainline/linux/commit/49e65645ab6cf8afd64455f9d97d365fcbd58a0e

```
CONFIG_CMDLINE="root=/dev/mmcblk0"
CONFIG_CMDLINE_FORCE=y
```

Maybe you're running into that?

**Comment by phodina** [comment]
> > So this is UART console just for the Kernel. I won't be able to see bootlog from the earlier stage of bootloader?
> 
> As said you should have already seen S1boot come across (if not, maybe something is wrong with the UART, or they disabled it "somehow"), I thought you were trying to see it from the SODP kernel.
> 
> At least that's what I observed on the Xperia X and Xperia XA2 Ultra: S1boot UART logs are always available, because that's outside the territory that we can modify.
> 
> > The interest is to run on Xperia XZ3 phone [PostmarketOS](https://wiki.postmarketos.org/wiki/Devices) - well port it first. The SDM845 is well supported.
> 
> I know. I contribute to the mainline kernel _daily_ with features and fixes, and hope pmOS starts using our efforts some day. No immediate need for UART, though.
> 
> What's the current status, and what kernel do you intend to use?

I can flash back the SODP kernel or LineageOS there and see if the UART really works. It was more like e.g. on Pixel device you need to enable it over `fastboot oem uart enable` and then see messages from start (they use the USB-C port, the SBU pins)

**Comment by phodina** [comment]
Okay, I'll try the repo.

Well I'm just doing `fastboot boot boot.img` as I'm reluctant to flash the kernel to UFS to not brick the device.

**Comment by MarijnS95** [comment]
Don't forget that Tama is a DTBO platform, so you'll either have to wipe that partition to prevent a bogus DTB from being overlaid (assuming you compile a plain-old appended-dtb kernel with everything in it), or supply a sensible devicetree in that partition.

**Comment by phodina** [comment]
So I should basically ditch the UART in favour of the SDcard, create image for the kernel, that's flashed through the fastboot into the boot slot.

Then the bootloader loads the kernel into the RAM and the kernel will load the rest from SDcard?

**Comment by phodina** [comment]
> Don't forget that Tama is a DTBO platform, so you'll either have to wipe that partition to prevent a bogus DTB from being overlaid (assuming you compile a plain-old appended-dtb kernel with everything in it), or supply a sensible devicetree in that partition.

Same on the Pixel line, I just flash empty DTBO there.

**Comment by MarijnS95** [comment]
> So I should basically ditch the UART in favour of the SDcard, create image for the kernel, that's flashed through the fastboot into the boot slot.

For starters you can use the pMOS ramdisk in your boot.img together with the kernel, someone sent me a very old build from pmOS and it was enough to get a `telnet` console over RNDIS.

So yes, I'd ditch the UART as you shouldn't really need it beyond initial bringup :crossed_fingers: - except if you work on the kernel a lot or update eagerly, it has a tendency to panic :)

> Then the bootloader loads the kernel into the RAM and the kernel will load the rest from SDcard?

If you want a functioning userspace after that, yes the ramdisk can eventually load userspace from a bigger partition - sdcard because you cannot use UFS.

(Afaik the kernel should also be able to boot into a `root=` partition without ramdisk, but I've never tried it)

**Comment by phodina** [comment]
Perfect, time to put the UART debugging connector to sleep.

I'll update the linux package with the kernel repo you sent and will try it on the device.

Thanks for the help!

**Comment by MarijnS95** [comment]
@phodina cool, keep us posted on the updates and Sony mainline bringups on pmOS in general! I have a long-standing TODO item to update various SoCs and Sony devices on the pmOS wiki, but actually fixing and contributing these to mainline Linux has so far been much more fun and rewarding, and is more important :)

(By the way it would still be interesting to get this UART situation figured out and working, but that should not be necessary for your mainline adventure)

**Comment by phodina** [comment]
Will do!

Just what's the best place to discuss these things? I assume there are more people interested.

**Comment by phodina** [comment]
Yeah I'd like to get the serial port as well but since I see you did a lot work on porting the changes to mainline the uart should not be needed for now.

Also rather keep the phone alive until the UFS "deadtrap" is solved.

**Comment by MarijnS95** [comment]
@phodina I was about to ask/suggest the same, the SODP bug-tracker isn't the right place but it's very important that we stay in touch, as for example the panel drivers and similar features for the XZ3 are not upstreamed yet but are fully working on our mainline fork (they are on the list though :stuck_out_tongue:).

I've previously been in the pmOS mainline IRC/Matrix channel, but it's been a useless cess-pool.

**Comment by phodina** [comment]
> @phodina we have more commits for Tama/XZ3 over at https://github.com/SoMainline/linux/commits/marijn/longbois-next, I booted that branch just this morning. There's also a defconfig.
> 
> You might be booting from an SDcard, and I had to explicitly force the cmdline to use `mmcblk0` because the bootloader cmdline otherwise takes preference:
> 
> [SoMainline/linux@49e6564](https://github.com/SoMainline/linux/commit/49e65645ab6cf8afd64455f9d97d365fcbd58a0e)
> 
> ```
> CONFIG_CMDLINE="root=/dev/mmcblk0"
> CONFIG_CMDLINE_FORCE=y
> ```
> 
> Maybe you're running into that?

So the `defconfig` should be sufficient configuration the get the XZ3 into bootable state?

https://github.com/SoMainline/linux/blob/49e65645ab6cf8afd64455f9d97d365fcbd58a0e/arch/arm64/configs/defconfig

**Comment by MarijnS95** [comment]
There's a more recent commit to the defconfig, you might want to take it from the HEAD of the https://github.com/SoMainline/linux/commits/marijn/longbois-next branch instead.

I think that defconfig should get it to boot, though I'd take the whole branch to get full-er functionality (e.g. working panel as I alluded to above).

Note that it's my personal development branch that's actively rebased on top of `-next`, contains a lot of cr4p and in-progress patches get pushed from time to time, for the entire range of Sony phones.

**Comment by phodina** [comment]
This should be enough so that the kernel does not even touch the UFS right?
https://github.com/SoMainline/linux/blob/0405d8392656b4ede0c1e71828a9a40a2562838a/arch/arm64/boot/dts/qcom/sdm845-sony-xperia-tama.dtsi#L781

And this is the right dts for the device.
https://github.com/SoMainline/linux/blob/marijn/longbois-next/arch/arm64/boot/dts/qcom/sdm845-sony-xperia-tama-akatsuki.dts

**Comment by MarijnS95** [comment]
Yes and yes.

**Comment by phodina** [comment]
> @phodina we have more commits for Tama/XZ3 over at https://github.com/SoMainline/linux/commits/marijn/longbois-next, I booted that branch just this morning. There's also a defconfig.
> 
> You might be booting from an SDcard, and I had to explicitly force the cmdline to use `mmcblk0` because the bootloader cmdline otherwise takes preference:
> 
> [SoMainline/linux@49e6564](https://github.com/SoMainline/linux/commit/49e65645ab6cf8afd64455f9d97d365fcbd58a0e)
> 
> ```
> CONFIG_CMDLINE="root=/dev/mmcblk0"
> CONFIG_CMDLINE_FORCE=y
> ```
> 
> Maybe you're running into that?

If I understand this correctly you used the whole SDcard as a partition without any MBR or GPT, correct?

**Comment by phodina** [comment]
Here are the commits for `akatsuki`. Will try to test it also on the real device.

To replicate the steps get [pmbootstrap](https://wiki.postmarketos.org/wiki/Pmbootstrap) and checkout my repo for `pmaports`. Select Sony -> akatsuki.

Then run `pmbootstrap export`. This exports the `bootimg` for the `boot` partition and the rootfs `sony-akatsuki.img ` which will go to the SD card.

https://gitlab.com/phodina/pmaports/-/commits/sony-sdm845-akatsuki

Use the `dtbo` and `vbmeta` from LineageOS
https://download.lineageos.org/devices/akatsuki/builds

**Comment by phodina** [comment]
Okay, so I first get the screen with the bootloader unlocked followed by the one with red warning that the device has been  corrupt. It can't be trusted and will not boot.

After it resets and is stuck in this bootloop.

**Comment by phodina** [comment]
And that was the reason why I also wanted UART to understand what's wrong ...

**Comment by konradybcio** [comment]
you need to flash this to dtbo (this is two zero bytes) and flash vbmeta with`fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img`
[dtbo_empty.zip](https://github.com/sonyxperiadev/kernel/files/11750399/dtbo_empty.zip)

**Comment by phodina** [comment]
Attempting to flash the `dtbo` you shared I get this error:
```
fastboot flash dtbo dtbo_empty
fastboot: error: ANDROID_PRODUCT_OUT not set
```

The `vbmeta` flashes correctly:
```
fastboot  --disable-verity --disable-verification flash vbmeta vbmeta.img
Rewriting vbmeta struct at offset: 0
Sending 'vbmeta' (8 KB)                            OKAY [  0.006s]
Writing 'vbmeta'                                   OKAY [  0.001s]
Finished. Total time: 0.018s
```

And the device is visible:
```
fastboot devices
QV711YZ01J	 fastboot
```

**Comment by phodina** [comment]
Okay, now it went also fine when I attempted for the second time
```
fastboot flash dtbo ~/Downloads/Sony/dtbo_empty.img
target reported max download size of 536870912 bytes
sending 'dtbo' (0 KB)...
OKAY [  0.002s]
writing 'dtbo'...
OKAY [  0.002s]
finished. total time: 0.004s
```

**Comment by Thaodan** [comment]
Konrad Dybcio ***@***.***> writes:

>> > @phodina you have to enable the console via kernel-devicetree
>> > and/or cmdline (see Android devicetree), and may even need to
>> > toggle a pin or two.
>> > More curiously, what are you intending to use the UART function for?
>> 
>> So this is UART console just for the Kernel. I won't be able to see
>> bootlog from the earlier stage of bootloader?
>> 
>> The interest is to run on Xperia XZ3 phone
>> [PostmarketOS](https://wiki.postmarketos.org/wiki/Devices) - well
>> port it first. The SDM845 is well supported.
>
> Just be careful with the UFS.. Enabling it on a non-SODP or non-stock
> kernel will irrecoverably kill your device (fw quirk)

Can you apply the quirk on mainline either with a kernel config option
or device tree option?

**Comment by phodina** [comment]
Good news, PostmarketOS boots :partying_face: 

![image](https://github.com/sonyxperiadev/kernel/assets/2997905/1071fdde-fc12-48f7-b056-12391f79fc17)


The issue was the vbmeta.img. In the end I used this one
https://github.com/bkerler/mtkclient/blob/main/vbmeta.img.empty

**Comment by phodina** [comment]
Another issue now is that the image generated by pmOS is sparse Android image so the CMDLINE argument for the kernel for `root=` needs to be little bit complicated or the image converted to `ext4` filesystem but that shouldn't be a big problem.

Thanks for the help!

**Comment by MarijnS95** [comment]
> Can you apply the quirk on mainline either with a kernel config option or device tree option?

Someone ported it, but no-one dared to sacrifice their devices to test it out!

Likewise, there was no consensus how to land this upstream, nor if some could accidentally break it when more UFS patches get merged in.

@thaodan is that a blocker for you/SfOS using mainline on Xperia (together with all the missing features that make it a phone thus far)?

**Comment by MarijnS95** [comment]
@phodina amazing! Eww to see that vbmeta thing, it's weird that `fastboot` needs it but we can at least tell AOSP to build a disabled one right from the get-go too.

**Comment by MarijnS95** [comment]
Also, that means DRM, DPU and Display Stream Compression is working for you :)

**Comment by MarijnS95** [comment]
> Attempting to flash the `dtbo` you shared I get this error:
> 
> ```
> fastboot flash dtbo dtbo_empty
> fastboot: error: ANDROID_PRODUCT_OUT not set
> ```

In this case it has to be a filename, or `fastboot` will try to resolve that name to a partition assuming it is in an AOSP build tree... which it is not because `ANDROID_PRODUCT_OUT` is not set :)

**Comment by phodina** [comment]
> Also, that means DRM, DPU and Display Stream Compression is working for you :)

I've packaged the firmware that I previously extracted from the device and it's SDM845 which got quite a lot of upstream patches into the kernel

https://gitlab.com/phodina/firmware-sony-akatsuki

**Comment by phodina** [comment]
Btw speaking of the "dreaded" Display Stream Compression ... the Pixel 3 has also DSC and I have not managed to make the screen turn on and display stuff. Is that portable or something specific to Sony device - the screen itself?

**Comment by MarijnS95** [comment]
The driver is not portable, but I can take a look and fix it for you, assuming it was generated with the actually-dreaded mdss panel generator from msm8916-mainline ;)

**Comment by phodina** [comment]
> @phodina amazing! Eww to see that vbmeta thing, it's weird that `fastboot` needs it but we can at least tell AOSP to build a disabled one right from the get-go too.

Well IMHO it's not the kernel but the bootloader in this case some fork of little kernel that has the avblib for verifying the vbmeta before it passes control to the kernel. At least that's what the `u-boot` can do. Haven't work with little kernel directly but seen the code.

**Comment by MarijnS95** [comment]
> I've packaged the firmware that I previously extracted from the device and it's SDM845 which got quite a lot of upstream patches into the kernel

Note that things like `a630_sqe.fw` are available upstream in `linux-firmware` (Dmitry even sent a PR to update that _today_).

**Comment by phodina** [comment]
> > @phodina amazing! Eww to see that vbmeta thing, it's weird that `fastboot` needs it but we can at least tell AOSP to build a disabled one right from the get-go too.
> 
> Well IMHO it's not the kernel but the bootloader in this case some fork of little kernel that has the avblib for verifying the vbmeta before it passes control to the kernel. At least that's what the `u-boot` can do. Haven't work with little kernel directly but seen the code.

Cool, but let's focus this time on Sony to get it into a working state and then get hand dirty with other devices :-D

**Comment by konradybcio** [comment]
note^2 you need the updated a630_seq.fw or the mainline driver will not accept it

**Comment by MarijnS95** [comment]
> > @phodina amazing! Eww to see that vbmeta thing, it's weird that `fastboot` needs it but we can at least tell AOSP to build a disabled one right from the get-go too.
> 
> Well IMHO it's not the kernel but the bootloader in this case some fork of little kernel that has the avblib for verifying the vbmeta before it passes control to the kernel. At least that's what the `u-boot` can do. Haven't work with little kernel directly but seen the code.

Nor was the kernel mentioned anywhere, it's `fastboot` that should be able to make a minimal "disabled" `vbmeta` without external dependencies IMO :)

**Comment by MarijnS95** [comment]
@phodina was https://github.com/sonyxperiadev/kernel/issues/2558#issuecomment-1592006974 supposed to quote a different comment, the one about fixing DSC on Pixel 3? pmOS folks seem to have lost interest when I last talked to them, but someone else got their hands on this device and might be trying to fix it™.

**Comment by phodina** [comment]
> > I've packaged the firmware that I previously extracted from the device and it's SDM845 which got quite a lot of upstream patches into the kernel
> 
> Note that things like `a630_sqe.fw` are available upstream in `linux-firmware` (Dmitry even sent a PR to update that _today_).

Aren't those files signed for the Trustzone and specific to each device? I guess they are for the same SoC from Qualcomm. But are they signed with same key for each device from different vendor?

I recall I had to put these files together from `mdt` and `bXX` files if I recall correctly using this tool

https://github.com/andersson/pil-squasher

**Comment by konradybcio** [comment]
MBN/MDTs are, SQE fw and GMU fw aren't

**Comment by phodina** [comment]
> note^2 you need the updated a630_seq.fw or the mainline driver will not accept it

Okay no problem, I can pack also the `linux-firmware` and pick just the `a630_seq.fw` rest can be from the dump of the firmware from the device.

**Comment by phodina** [comment]
> @phodina was [#2558 (comment)](https://github.com/sonyxperiadev/kernel/issues/2558#issuecomment-1592006974) supposed to quote a different comment, the one about fixing DSC on Pixel 3? pmOS folks seem to have lost interest when I last talked to them, but someone else got their hands on this device and might be trying to fix it™.

There are few people who have it myself included as I used GrapheneOS on that device but since they and Google dropped support I attempted to get it working unfortunately without any luck to get the screen working

And it quoted the wrong comment, sorry for confusion

**Comment by MarijnS95** [comment]
> I recall I had to put these files together from `mdt` and `bXX` files if I recall correctly using this tool

For completentess the firmware loader supports split-mdt (the `.bXX`) files if you point `firmware-name` and other hardcoded paths to `.mdt` files (or symlink the `.mbn` file to `.mdt`) but it seems everyone prefers a pre-merged file nowadays (less clutter, no point doing multiple file lookups).

**Comment by phodina** [comment]
So let's also get back to the discussion question where to discuss the next progress?

The issue tracker on Github is nice to get it booting :tada: but not the best place to continue IMHO.

**Comment by phodina** [comment]
> MBN/MDTs are, SQE fw and GMU fw aren't

Found the commit, so both can be added to the firmware?
```
commit 88ea23e7eed04e78111013df9b81dd851037e4da
Author: Nicolas Dechesne <nicolas.dechesne@linaro.org>
Date:   Mon Sep 9 18:13:55 2019 +0200

    qcom: add firmware files for Adreno a630

    Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>

diff --git a/WHENCE b/WHENCE
index f7a61f03..6f364c3f 100644
--- a/WHENCE
+++ b/WHENCE
@@ -4441,6 +4441,8 @@ File: qcom/a530_zap.b00
 File: qcom/a530_zap.b01
 File: qcom/a530_zap.b02
 File: qcom/a530_zap.mdt
+File: qcom/a630_gmu.bin
+File: qcom/a630_sqe.fw

 Licence: Redistributable. See LICENSE.qcom and qcom/NOTICE.txt for details
```

does it mean that other SDM845 can use it also if they run mainline kernel?

**Comment by phodina** [comment]
Regarding the UFS, I have lab at work where we had for some R&D to do also reballing of BGA chips. I've found UFS Flash chips for about $20 - 64GB. 

Would it be possible to to dump the whole UFS off the phone then flash it to the new chip and solder on the board instead of the dead one?

If not it will be easier to just find a cheap phone on the ebay then.

Speaking of that I noticed that the Xperia XZ2 also has SDM845. Was there any reason why Sony did two phones on the same SoC?

Does the panel on the XZ2 have support in the mainline kernel? I guess the UFS issue is also present there right?

**Comment by phodina** [comment]
Good thing is that when the `debug-shell` is added to the initramfs there's Ethernet over USB connection.

I checked the `dmesg` log and it's able to see the SD card controller.
```
sdhci: Secure Digital Host Controller Interface driver
sdhci: Copyright(c) Pierre Ossman
sdhci-pltfm: SDHCI platform and OF driver helper
```

**Comment by jerpelea** [comment]
> So let's also get back to the discussion question where to discuss the next progress?
> 
> The issue tracker on Github is nice to get it booting 🎉 but not the best place to continue IMHO.

@phodina let's move it [here](https://github.com/sonyxperiadev/bug_tracker/) so that other people can have a reference

**Comment by Thaodan** [comment]
Alin Jerpelea ***@***.***> writes:

>> So let's also get back to the discussion question where to discuss the next progress?
>> 
>> The issue tracker on Github is nice to get it booting 🎉 but not the
>> best place to continue IMHO.
>
> lets keep it [here](https://github.com/sonyxperiadev/bug_tracker/) so
> that other people can have a reference

Would fit https://github.com/SoMainline/MainlineAndroidPorting or
someone other repo at SoMainline better?
