### ISSUE TITLE
Xperia 10 IV PMIC driver 

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#2562]
It seems that the PMIC driver is broken and charging is very intermittent sometimes it'll fast charge sometimes it won't, I have tried some of the commits here on a non-SODP kernel but doesn't seem to help, and some of the commits for PMIC driver doesn't allow the device to boot

**Comment by bartcubbins** [comment]
Recently the kernel has come into shape and support for this device has improved significantly, you should try it again.

Also, you should use a [bug tracker](https://github.com/sonyxperiadev/bug_tracker) for reports, otherwise your reports may go unnoticed, thanks.

**Comment by ghost** [comment]
I will try again soon

**Comment by jerpelea** [comment]
please use the bugtracker
