### ISSUE TITLE
the phone will not boot

### ISSUE THREAD

**Issue by pawcioo132** [sonyxperiadev/kernel#347]
Hi, i try to compile aosp 5.1.1 for eagle like in sony's guide but after success compile and flash to phone, my xperia d2303 don't boot it's only one short vibrate and thats all.

**Comment by galaxyfreak** [comment]
Strange, please recheck that kernel has been bulit with DTs successfully packed and included.

**Comment by jerpelea** [comment]
You have to flash latest sw release first and after you have to flash the open devices bootloader (with recovery)

**Comment by pawcioo132** [comment]
i aready try that, i think problem is with DTs beacause on the end compiling kernel i have messenge "nothink to do with DTs ..." 
and next line is: "/android/kernel/sony/msm/arch/arm/boot/dts/makefile:228: warning: overriding for target 'dtbs' "
"/android/kernel/sony/msm/arch/arm/boot/dts/makefile:228: warning: ignoring old commands target 'dtbs' " 
also i add its build from fresh source, and first build.

**Comment by galaxyfreak** [comment]
Do FXP builds boot for you?

**Comment by kholk** [comment]
I agree with that question, knowing if FXP (complete, prebuilt) builds are booting is really important.

If you've got the latest bootloader and FXP builds are booting, then the problem happens on your local build, perhaps your build system may have something wrong.

In case those won't boot, then there's some unknown kernel problem. Btw, "one short vibrate and that's all" sounds like really early fail. About your DTBs messages, those should be nothing fatal.

**Comment by pawcioo132** [comment]
Yes FXP build booted success for me, I use his build right now.

**Comment by pawcioo132** [comment]
It's look like after vibrate phone will power off. because when I hold power button longer this short vibrations are repeat after 2 - 3 second. Maybe this information will be little helpful for you.

**Comment by pawcioo132** [comment]
Okey sorry for problem but that issue was beacause i don't have some package in my build system and kernel build was not fully completed successfully.

**Comment by nos1609** [comment]
I'm facing the same issue. @pawcioo132 What was the missing component?
