### ISSUE TITLE
Inline kernel fails to build, due to missing dtbs in output folder

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/kernel#535]
Kernel fails to build inline because the dtbs folder is not copied to output directory

```
mkqcdtbootimg: failed to open '/out/target/product/aries/dtbs': No such file or directory
build/core/Makefile:566: recipe for target '/out/target/product/aries/boot.img' failed
make: *** [/out/target/product/aries/boot.img] Error 1
```

Android.mk I believe is the culprit:
https://github.com/sonyxperiadev/kernel/blob/misc-dev/Android.mk#L61
and,
https://github.com/sonyxperiadev/kernel/blob/misc-dev/Android.mk#L135

**Comment by rancidfrog** [comment]
When **BUILD_KERNEL := true**
`BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/dtbs`
Should be
`BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/obj/KERNEL_OBJ/arch/arm/boot/dts`
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/BoardConfig.mk#L117
https://github.com/sonyxperiadev/device-sony-shinano/blob/master/BoardConfig.mk#L39
Maybe default should be:
`BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/obj/KERNEL_OBJ/arch/arm/boot/dts`
And, KernelConfig.mk, https://github.com/sonyxperiadev/vendor-sony-kernel/blob/master/KernelConfig.mk , is changing to **BUILD_KERNEL := false** it should change output to
`BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/dtbs`

**Comment by mengxiaoxi** [comment]
hi

1 check if you have downloaded and extracted prebuilt kernel in
vendor/sony/kernel folder

2 it should be boot.img  insteadof bootimg...
2015年12月27日 下午11:21，"rancidfrog" notifications@github.com写道：

**Comment by rancidfrog** [comment]
That is translation problem, you using translator google?
Vendor/sony/kernel is for aosp only.
And, guideline should be followed: 

```
BUILD_KERNEL := true
-include vendor/sony/kernel/KernelConfig.mk
```

Kernelconfig.mk Should change output folder to: BOARD_MKBOOTIMG_ARGS += --dt_dir $(OUT)/dtbs
The same way it changes build_kernel to false.
Because, if kernel project not included, build kernel is true, which will need output folder to be: $(OUT)/obj/KERNEL_OBJ/arch/arm/boot/dts

**Comment by rancidfrog** [comment]
With new appended dtb not needed anymore

**Comment by Mikdadali** [comment]
pls help
![image](https://user-images.githubusercontent.com/10883393/78228581-82930b00-74ec-11ea-95ab-2477fca953f4.png)

![image](https://user-images.githubusercontent.com/10883393/78228599-8b83dc80-74ec-11ea-99b2-9ff18b159a7d.png)

![image](https://user-images.githubusercontent.com/10883393/78228634-93dc1780-74ec-11ea-9c05-9e7c8a6485ca.png)
