### ISSUE TITLE
What is device_defconfig for Xperia C ??

### ISSUE THREAD

**Issue by deepsidhu1313** [sonyxperiadev/kernel#632]
Hi, i am trying to build Android 6 for xperia C. Can you tell me what is device_defconfig for this device ??

**Comment by galaxyfreak** [comment]
There's no support for Xperia C here.

**Comment by deepsidhu1313** [comment]
Sir, As you are an expert developer of Sony. Can you point me to the correct literature so that i can build Android 6 for the device?

I will be very grateful :smiley:

**Comment by jerpelea** [comment]
Xpera c is not supported by Open Devices Project and there is no easy way of building android for your device.

**Comment by deepsidhu1313** [comment]
Thank you @galaxyfreak @jerpelea  :smile:
