### ISSUE TITLE
fatal error: cyttsp4_img.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#662]
I compile the kernel to flash (recover) touchscreen controller. But the error appears in the assembly. With no source controller firmware file (cyttsp4_img.h).

Where can I get cyttsp4_img.h for my  xperia T3 D5103 (seagull)? 

> CC      drivers/input/touchscreen/cyttsp4/cyttsp4_platform.o
> drivers/input/touchscreen/cyttsp4/cyttsp4_platform.c:38:25: fatal error: cyttsp4_img.h: No such file or directory
> # include "cyttsp4_img.h"
> 
> ```
>                      ^
> ```
> 
> compilation terminated.
> make[4]: **\* [drivers/input/touchscreen/cyttsp4/cyttsp4_platform.o] Ошибка 1
> make[3]: **\* [drivers/input/touchscreen/cyttsp4] Ошибка 2
> make[2]: **\* [drivers/input/touchscreen] Ошибка 2
> make[1]: **\* [drivers/input] Ошибка 2
> make: **\* [drivers] Ошибка   2

**Comment by jerpelea** [comment]
the TS firmware should not be flashed or you risk to damage your device!
to update the firmware just flash the latest Sony official software and let the phone boot
