### ISSUE TITLE
Z3 Tablet Compact dtb not found

### ISSUE THREAD

**Issue by nos1609** [sonyxperiadev/kernel#674]
Trying compiling kernel for SGP621 using both [CM](https://github.com/CyanogenMod/android_kernel_sony_msm) and kernel-aosp-LA.BF64.1.2.2_rb4.7 branch. Thr final result fails hotbooting over fastboot and have similars sympthoms as found in Issue #347 

> ~/D/kernel-aosp-LA.BF64.1.2.2_rb4.7 » fastboot boot boot.img
> < waiting for any device >
> downloading 'boot.img'...
> OKAY [  0.302s]
> booting...
> FAILED (remote: dtb not found)
> finished. total time: 0.385s

Trying flashing the kernel over fastboot results  in a short vibro and no other sign of life...
Exactly the same thing with scorpion_windy aka SGP611.

Also interesting, that the kernel compiled with the same sources but with the Z3 leo defconfigs boots up, and even enters into recovery, with no LCD as expected on a slyghtly different hardware. And there is no warning trying hotbooting it over fastboot.

Might suppose that there is an issue with device tree for scorpion models.

**Comment by jerpelea** [comment]
how are you compiling? i have tested and the kernel builds and boots fine 
the windy devices use the same config as the GSM models
