### ISSUE TITLE
Aosp for Xperia m4 aqua doesn't boot 

### ISSUE THREAD

**Issue by diyari95** [sonyxperiadev/kernel#824]
Hi we have issue of booting aosp for xperia m4, we tried many times compiling again but it just doesn't boot up,  we need to be fixed, thanks

**Comment by renj1ete0** [comment]
Can confirm issue still persists, there is no working method of using unified kernel to build and boot with instructions followed, only prebuilt works on select random devices across all variants (ie. one user with E2303 boots into AOSP but the next does not)

**Comment by pablomh** [comment]
It's not working even with latest device and vendor source code/blobs...

**Comment by bartcubbins** [comment]
@jerpelea can be closed
