### ISSUE TITLE
No Baseband (No signal on Xperia Z2 ['sirius])

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#843]
Everything seems to be working except for Baseband.

**Comment by ghost** [comment]
bump

**Comment by max1220** [comment]
Same here on Z1C, dmesg says something about missing modem firmware, I suspect the 3.10 kernel does not have working modem firmware yet :(

**Comment by alviteri** [comment]
Pick modem blobs from stock .... Sony can't provide them

**Comment by max1220** [comment]
I'm pretty sure you can obtain firmware from here:
http://developer.sonymobile.com/open-devices/list-of-devices-and-resources/
BTW, my problem somehow solved itself after a clean reflash of FXP's latest AOSP 6 for my device. I have no clue how or why.

**Comment by Kali-** [comment]
as alvitiery wrote, modem and some other firmware is not available for download
