### ISSUE TITLE
KCAL support?

### ISSUE THREAD

**Issue by leeoniya** [sonyxperiadev/kernel#882]
Hey guys,

Would you consider adding support for KCAL [1]? I'm finding that the screen on my Z5C (suzuran) is way oversaturated and there are no apps to adjust vibrance/intensity/saturation, only contrast, temperature and RGB balance (which already works fine in CM13's display settings). This feature would be really great.

thanks!

[1] http://forum.xda-developers.com/android/software-hacking/dev-kcal-advanced-color-control-t3032080

**Comment by scafroglia93** [comment]
Are you still interested ?

**Comment by leeoniya** [comment]
The CM13/AOSP kernel had too many issues on the Z5C (camera issues, call volume/echo). I had to resort to the XPower v5.0 modified stock rom with a sunkernel [1] which seems to have the KCAL patches.

![screenshot_20170107-212918](https://cloud.githubusercontent.com/assets/43234/21747058/6ce2490c-d520-11e6-9fec-10b84daefd95.png)

[1] https://forum.xda-developers.com/z5-compact/development/kernel-zachs-kernel-playground-z5c-wip-t3350690/page20

**Comment by leeoniya** [comment]
...that being said, if CM (i guess LineageOS now) or another lightweight AOSP rom presents itself without all the driver bugs, i would be interested in switching. so yes, it would be nice to have these patches especially if it's not a lot of work.

**Comment by scafroglia93** [comment]
This is my personal branch based on 1.3.3 with Kcal V2 fully functional on my Z3 Aosp

https://github.com/scafroglia93/kernel/tree/kcal

**Comment by leeoniya** [comment]
i'm not an android dev, so unless these patches make it into some actively maintained (or recent) and flashable Z5C kernel [or downstreamed as part of a Z5C rom] they won't affect me.

i guess the first step would be to submit a PR into this repo :/

**Comment by scafroglia93** [comment]
Yep but it's really hard to merge this into master repo

**Comment by leeoniya** [comment]
`¯\_(ツ)_/¯`

**Comment by bartcubbins** [comment]
unfortunately I think we will never get KCAL support on our 1.3.3 AOSP kernel, sorry.
@jerpelea can it be closed?
