### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#883]
http://pastebin.com/WZpPCMCC (Same error happens when building the system)

I'm using SonyAosp to build Android 7.0.0 (https://github.com/SonyAosp/platform_manifest)

**Comment by kholk** [comment]
Your system misses the lzop program. You have to install this dependency on your Linux distribution using your package manager (dpkg, portage, whatever)

**Comment by ghost** [comment]
Thanks, recovery image built successfully now. I will keep this issue open because I'm building the system now and if any error occurs then i'll report back.

**Comment by ghost** [comment]
Everything built successfully and flashed onto my device :)
