### ISSUE TITLE
Z3 Camera Issue on N

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#885]
![5105420208013454623-account_id 1](https://cloud.githubusercontent.com/assets/18221207/18612273/42ffc61e-7d0a-11e6-8482-81d77b97d6e3.jpg)

using everything recommended from Sony to build aosp rom. UsingSW_binaries_for_Xperia_AOSP_M_MR1_v04 blobs.

**Comment by mcgi5sr2** [comment]
can confirm the front camera has the reverse of this (ie green on the right). Are there new blobs incoming for the shinano boards?
Video also FCs the apk, but it does create an empty video file.
http://pastebin.com/SDTcvhyi

**Comment by jerpelea** [comment]
fixed
