### ISSUE TITLE
Some issues on Xperia Z2 (D6503, SonyAosp)

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#904]
1) When switching off the Flashlight it makes a noise, sometimes the QS tile for the Flashlight disappears.

Also, when using the "Super-Bright LED Torch" application from the Google Play Store, it creates an error message below :

"It's detected that your hardware does not support LED Cam light. Screen brightness will be used to light up."

2) There is a 'Charging issue'... when you plug the USB cable to your phone it charges the phone but when you remove the USB cable, it will stop charging the phone but the system still thinks that the device is charging.

^^ So, when you switch off the phone, you won't be able to turn on the phone using the power button. You've to press the "Power button + Volume Up button" to completely stop all the power from the board and then you can power on your phone by using the "Power button"

**Comment by rcstar6696** [comment]
1. Is due a very unstable camera on android N 
2. Yes its the currently biggest issue i hope @kholk can help with a fix for it

**Comment by scafroglia93** [comment]
Same problem on Z3

**Comment by RyTekk** [comment]
"sometimes the QS tile for the Flashlight disappears"
Even this happens on latest Z5 Dual firmware 32.2.A.5.11

**Comment by bartcubbins** [comment]
@danielhoset27 did it can be closed or you still have this problem?
