### ISSUE TITLE
Boot logo on amami is not like one from stock kernel, its big

### ISSUE THREAD

**Issue by munjeni** [sonyxperiadev/kernel#918]
https://github.com/sonyxperiadev/kernel/blob/aosp/LA.BR.1.3.3_rb2.14/drivers/video/msm/mdss/mdss_mdp_splash_logo.c#L39

you must change line 39 to CONFIG_MACH_SONY_AMAMI_ROW since CONFIG_MACH_SONY_AMAMI not exists and kernel uses 480.h splash screen as a default which cause big logo on amami!

**Comment by jerpelea** [comment]
pr the change
