### ISSUE TITLE
After connecting to wall charger, usb unusable no debug and icon remains charging

### ISSUE THREAD

**Issue by rancidfrog** [sonyxperiadev/kernel#934]
Aries, N, 1.3.3 branch
Connecting to charger makes USB unusable - no adb detection . . .
Connecting to computer does not have same issue.

After removing USB from charger, battery icon remains as charging

When charging with phone switched off,
After showing charging animation the screen remains black but with full brightness,
The above issue also seems to be a problem, when removed from charger phone display remains on maximum brightness.

**Comment by ItzLevvie** [comment]
Confirmed on sirius cm14

**Comment by ItzLevvie** [comment]
Confirmed on Sirius (CM14)

**Comment by rancidfrog** [comment]
https://github.com/sonyxperiadev/kernel/pull/948 Fixes issue on shinano aries
